[2021-03-09 18:33:53,369] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 18:33:55,602] [log.py:224] [log:log_response] [WARNING]- Not Found: /
[2021-03-09 18:33:55,603] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET / HTTP/1.1" 404 179
[2021-03-09 18:33:55,725] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-03-09 18:34:00,121] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
[2021-03-09 18:34:00,151] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 3742
[2021-03-09 18:34:00,199] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/img/logo.png HTTP/1.1" 200 115997
[2021-03-09 18:34:00,241] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/img/bg.svg HTTP/1.1" 200 9547
[2021-03-09 18:34:01,655] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2021-03-09 18:34:01,710] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 22265
[2021-03-09 18:34:01,762] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/css/index.css?_=3.2 HTTP/1.1" 200 7134
[2021-03-09 18:34:01,778] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/segment.js?_=2021.3 HTTP/1.1" 200 1186
[2021-03-09 18:34:01,785] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/cookie.js?_=2021.3 HTTP/1.1" 200 524
[2021-03-09 18:34:01,787] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/en-us.js?_=2021.3 HTTP/1.1" 200 811
[2021-03-09 18:34:01,792] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/dicts.js?_=2021.3 HTTP/1.1" 200 6190
[2021-03-09 18:34:01,796] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/theme/theme.js?_=2021.3 HTTP/1.1" 200 4274
[2021-03-09 18:34:01,800] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/menu.js?_=2021.3 HTTP/1.1" 200 2089
[2021-03-09 18:34:01,801] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/zh-hans.js?_=2021.3 HTTP/1.1" 200 1254
[2021-03-09 18:34:01,801] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/waves/waves.min.js?_=2021.3 HTTP/1.1" 200 6329
[2021-03-09 18:34:01,803] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/index.js?_=2021.3 HTTP/1.1" 200 20820
[2021-03-09 18:34:04,225] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/user/useranotherconfig/ HTTP/1.1" 200 23836
[2021-03-09 18:34:04,259] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/language.js?_=2.1.2 HTTP/1.1" 200 189
[2021-03-09 18:34:04,263] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/en-us.js?_=2.1.2 HTTP/1.1" 200 811
[2021-03-09 18:34:04,277] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7732
[2021-03-09 18:34:04,284] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/jquery/jquery.min.js HTTP/1.1" 200 89476
[2021-03-09 18:34:04,295] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[2021-03-09 18:34:04,305] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/js/core.js HTTP/1.1" 200 5418
[2021-03-09 18:34:04,306] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/js/actions.min.js HTTP/1.1" 200 3237
[2021-03-09 18:34:04,308] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate.min.js HTTP/1.1" 200 388
[2021-03-09 18:34:04,309] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/js/urlify.js HTTP/1.1" 200 8632
[2021-03-09 18:34:04,310] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 200 125266
[2021-03-09 18:34:04,310] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6078
[2021-03-09 18:34:04,455] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[2021-03-09 18:34:04,994] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/user/usermodel/ HTTP/1.1" 200 23820
[2021-03-09 18:34:05,045] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7732
[2021-03-09 18:34:05,864] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/user/usermodel/add/ HTTP/1.1" 200 17925
[2021-03-09 18:34:05,889] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7732
[2021-03-09 18:34:05,905] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
[2021-03-09 18:34:05,908] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[2021-03-09 18:34:05,908] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/css/widgets.css HTTP/1.1" 200 10333
[2021-03-09 18:34:08,536] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/user/usermodel/ HTTP/1.1" 200 23820
[2021-03-09 18:34:08,583] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7732
[2021-03-09 18:35:19,699] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:27:11,637] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:27:17,043] [log.py:224] [log:log_response] [WARNING]- Not Found: /
[2021-03-09 20:27:17,044] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET / HTTP/1.1" 404 179
[2021-03-09 20:27:17,166] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-03-09 20:27:41,925] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/ HTTP/1.1" 200 5998
[2021-03-09 20:27:41,997] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[2021-03-09 20:27:42,007] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2021-03-09 20:27:42,008] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[2021-03-09 20:27:42,012] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2021-03-09 20:27:42,013] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2021-03-09 20:27:42,016] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2021-03-09 20:27:42,017] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[2021-03-09 20:27:42,019] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2021-03-09 20:27:42,020] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2021-03-09 20:27:42,022] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[2021-03-09 20:27:42,036] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[2021-03-09 20:27:43,910] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/User/ HTTP/1.1" 200 10943
[2021-03-09 20:27:43,954] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
[2021-03-09 20:27:52,775] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/User/ HTTP/1.1" 201 9466
[2021-03-09 20:28:13,385] [log.py:224] [log:log_response] [WARNING]- Bad Request: /api/User/
[2021-03-09 20:28:13,386] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/User/ HTTP/1.1" 400 9439
[2021-03-09 20:29:32,721] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/views.py changed, reloading.
[2021-03-09 20:29:33,180] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:32:40,900] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/NovelProject/settings.py changed, reloading.
[2021-03-09 20:32:41,336] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:33:23,218] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:33:53,409] [log.py:224] [log:log_response] [WARNING]- Not Found: /api/user/1/PhoneCode/
[2021-03-09 20:33:53,409] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/user/1/PhoneCode/ HTTP/1.1" 404 9604
[2021-03-09 20:34:03,035] [log.py:224] [log:log_response] [WARNING]- Method Not Allowed: /api/
[2021-03-09 20:34:03,036] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/ HTTP/1.1" 405 46
[2021-03-09 20:34:07,263] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/ HTTP/1.1" 200 271
[2021-03-09 20:34:14,513] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/User/ HTTP/1.1" 200 11256
[2021-03-09 20:34:15,608] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-03-09 20:34:28,700] [log.py:224] [log:log_response] [WARNING]- Not Found: /api/user/1/
[2021-03-09 20:34:28,700] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /api/user/1/ HTTP/1.1" 404 9573
[2021-03-09 20:34:39,417] [log.py:224] [log:log_response] [WARNING]- Not Found: /api/user/
[2021-03-09 20:34:39,418] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /api/user/ HTTP/1.1" 404 9567
[2021-03-09 20:34:46,902] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:34:52,124] [log.py:224] [log:log_response] [WARNING]- Not Found: /
[2021-03-09 20:34:52,127] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET / HTTP/1.1" 404 2605
[2021-03-09 20:34:57,387] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/ HTTP/1.1" 200 5964
[2021-03-09 20:34:57,452] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[2021-03-09 20:34:59,112] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/User/ HTTP/1.1" 200 11256
[2021-03-09 20:35:13,619] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/User/ HTTP/1.1" 200 9607
[2021-03-09 20:35:18,817] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/User/ HTTP/1.1" 200 11689
[2021-03-09 20:35:22,229] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/User/2/ HTTP/1.1" 200 11969
[2021-03-09 20:35:30,039] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/User/2/ HTTP/1.1" 200 220
[2021-03-09 20:35:33,426] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/User/1/ HTTP/1.1" 200 130
[2021-03-09 20:35:46,020] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/User/2/PhoneCode/
Traceback (most recent call last):
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/adminuser/PycharmProjects/NovelProject/apps/user/views.py", line 100, in PhoneCode
    return Response(BaseResponse(Message=ResponseMessage.NullMessage.value).__str__(),
  File "/home/adminuser/PycharmProjects/NovelProject/BaseConfig/Response.py", line 14, in __str__
    if len(self.Phone) == 0:
TypeError: object of type 'NoneType' has no len()
[2021-03-09 20:35:46,021] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /api/User/2/PhoneCode/ HTTP/1.1" 500 100943
[2021-03-09 20:36:46,901] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/User/1/ HTTP/1.1" 200 130
[2021-03-09 20:36:56,360] [log.py:224] [log:log_response] [WARNING]- Not Found: /api/User/1/set_phone_code/
[2021-03-09 20:36:56,360] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /api/User/1/set_phone_code/ HTTP/1.1" 404 9618
[2021-03-09 20:37:11,657] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/User/2/PhoneCode/ HTTP/1.1" 200 48
[2021-03-09 20:37:22,627] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/User/2/PhoneCode/
Traceback (most recent call last):
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/adminuser/PycharmProjects/NovelProject/apps/user/views.py", line 100, in PhoneCode
    return Response(BaseResponse(Message=ResponseMessage.NullMessage.value).__str__(),
  File "/home/adminuser/PycharmProjects/NovelProject/BaseConfig/Response.py", line 14, in __str__
    if len(self.Phone) == 0:
TypeError: object of type 'NoneType' has no len()
[2021-03-09 20:37:22,628] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /api/User/2/PhoneCode/ HTTP/1.1" 500 101080
[2021-03-09 20:37:45,653] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/BaseConfig/Response.py changed, reloading.
[2021-03-09 20:37:46,104] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:37:46,453] [log.py:224] [log:log_response] [WARNING]- Unauthorized: /api/User/2/PhoneCode/
[2021-03-09 20:37:46,453] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /api/User/2/PhoneCode/ HTTP/1.1" 401 9484
[2021-03-09 20:37:46,480] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2021-03-09 20:37:46,492] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2021-03-09 20:37:46,495] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2021-03-09 20:37:46,499] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2021-03-09 20:37:46,502] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2021-03-09 20:37:46,503] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2021-03-09 20:37:51,309] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/User/2/PhoneCode/ HTTP/1.1" 200 48
[2021-03-09 20:38:06,716] [log.py:224] [log:log_response] [WARNING]- Unauthorized: /api/User/2/PhoneCode/
[2021-03-09 20:38:06,717] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/User/2/PhoneCode/ HTTP/1.1" 401 48
[2021-03-09 20:38:18,212] [log.py:224] [log:log_response] [WARNING]- Unauthorized: /api/User/2/PhoneCode/
[2021-03-09 20:38:18,213] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/User/2/PhoneCode/ HTTP/1.1" 401 48
[2021-03-09 20:39:09,104] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:42:31,145] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/BaseConfig/Models.py changed, reloading.
[2021-03-09 20:42:31,694] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:42:55,431] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/BaseConfig/Models.py changed, reloading.
[2021-03-09 20:42:55,828] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:43:48,135] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/BaseConfig/Models.py changed, reloading.
[2021-03-09 20:43:48,520] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:44:24,345] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
[2021-03-09 20:44:24,368] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 3742
[2021-03-09 20:44:24,445] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/css/login.css?_=2.1 HTTP/1.1" 200 500
[2021-03-09 20:44:24,455] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/particles/particles.js HTTP/1.1" 304 0
[2021-03-09 20:44:24,462] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/login.js?_=3.3 HTTP/1.1" 200 669
[2021-03-09 20:44:24,467] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/particles/app.js HTTP/1.1" 304 0
[2021-03-09 20:44:24,468] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/img/logo.png HTTP/1.1" 200 115997
[2021-03-09 20:44:24,495] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/img/bg.svg HTTP/1.1" 200 9547
[2021-03-09 20:44:25,966] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2021-03-09 20:44:26,036] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 22265
[2021-03-09 20:44:26,155] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/en-us.js?_=2021.3 HTTP/1.1" 200 811
[2021-03-09 20:44:26,167] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/zh-hans.js?_=2021.3 HTTP/1.1" 200 1254
[2021-03-09 20:44:26,168] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/waves/waves.min.css?_=2.1 HTTP/1.1" 200 3861
[2021-03-09 20:44:26,169] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/css/index.css?_=3.2 HTTP/1.1" 200 7134
[2021-03-09 20:44:28,707] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/user/usermodel/ HTTP/1.1" 200 24548
[2021-03-09 20:44:28,753] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/cookie.js HTTP/1.1" 200 524
[2021-03-09 20:44:28,755] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/css/changelists.css?_=20180905 HTTP/1.1" 200 6305
[2021-03-09 20:44:28,779] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[2021-03-09 20:44:28,786] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/js/actions.js HTTP/1.1" 200 6783
[2021-03-09 20:44:28,824] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[2021-03-09 20:44:28,827] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7732
[2021-03-09 20:44:28,829] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[2021-03-09 20:44:28,928] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[2021-03-09 20:44:29,255] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/user/useranotherconfig/ HTTP/1.1" 200 23820
[2021-03-09 20:44:29,297] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7732
[2021-03-09 20:44:30,248] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/user/useranotherconfig/add/ HTTP/1.1" 200 19423
[2021-03-09 20:44:30,277] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/js/calendar.js HTTP/1.1" 200 7788
[2021-03-09 20:44:30,279] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19750
[2021-03-09 20:44:30,279] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7732
[2021-03-09 20:44:30,283] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[2021-03-09 20:44:30,284] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[2021-03-09 20:44:30,472] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[2021-03-09 20:44:30,474] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[2021-03-09 20:44:36,144] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/user/useranotherconfig/ HTTP/1.1" 200 23820
[2021-03-09 20:44:36,182] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7732
[2021-03-09 20:45:16,727] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 22265
[2021-03-09 20:45:16,766] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/dicts.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:16,777] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/cookie.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:16,778] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/en-us.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:16,782] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/theme/theme.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:16,783] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/menu.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:16,784] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/segment.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:16,785] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/zh-hans.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:16,786] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/waves/waves.min.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:16,810] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/index.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:16,810] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/img/logo.png HTTP/1.1" 304 0
[2021-03-09 20:45:16,980] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/user/useranotherconfig/ HTTP/1.1" 200 23820
[2021-03-09 20:45:17,015] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7732
[2021-03-09 20:45:18,527] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 22265
[2021-03-09 20:45:18,554] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/theme/theme.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:18,555] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/zh-hans.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:18,555] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/dicts.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:18,559] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/segment.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:18,559] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/cookie.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:18,559] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/waves/waves.min.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:18,561] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/menu.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:18,561] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/en-us.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:18,564] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/index.js?_=2021.3 HTTP/1.1" 304 0
[2021-03-09 20:45:18,571] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/img/logo.png HTTP/1.1" 304 0
[2021-03-09 20:45:18,754] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/user/useranotherconfig/ HTTP/1.1" 200 23820
[2021-03-09 20:45:18,800] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7732
[2021-03-09 20:45:20,692] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/user/usermodel/ HTTP/1.1" 200 24548
[2021-03-09 20:45:20,718] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7732
[2021-03-09 20:45:23,144] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/user/useranotherconfig/add/ HTTP/1.1" 200 19423
[2021-03-09 20:45:23,164] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7732
[2021-03-09 20:45:37,842] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/user/useranotherconfig/ HTTP/1.1" 200 23820
[2021-03-09 20:45:37,869] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7732
[2021-03-09 20:48:44,601] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/views.py changed, reloading.
[2021-03-09 20:48:45,116] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:48:45,580] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/user/useranotherconfig/add/ HTTP/1.1" 200 19423
[2021-03-09 20:48:46,255] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/user/useranotherconfig/ HTTP/1.1" 200 23820
[2021-03-09 20:48:48,591] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2021-03-09 20:48:48,614] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 22265
[2021-03-09 20:48:49,241] [log.py:224] [log:log_response] [WARNING]- Unauthorized: /api/User/2/PhoneCode/
[2021-03-09 20:48:49,241] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /api/User/2/PhoneCode/ HTTP/1.1" 401 9518
[2021-03-09 20:48:50,501] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/User/2/ HTTP/1.1" 200 12003
[2021-03-09 20:48:53,103] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/ HTTP/1.1" 200 6147
[2021-03-09 20:48:55,178] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/ HTTP/1.1" 200 6147
[2021-03-09 20:48:55,194] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2021-03-09 20:48:55,197] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2021-03-09 20:48:55,208] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2021-03-09 20:48:55,210] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2021-03-09 20:48:55,212] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2021-03-09 20:48:55,215] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2021-03-09 20:48:56,480] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/ HTTP/1.1" 200 10527
[2021-03-09 20:49:58,692] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/Serializers.py changed, reloading.
[2021-03-09 20:49:59,128] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:49:59,630] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/ HTTP/1.1" 200 10977
[2021-03-09 20:49:59,648] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2021-03-09 20:49:59,657] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2021-03-09 20:49:59,661] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2021-03-09 20:49:59,662] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2021-03-09 20:49:59,668] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2021-03-09 20:49:59,668] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2021-03-09 20:52:43,714] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/views.py changed, reloading.
[2021-03-09 20:52:44,163] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:52:44,900] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/ HTTP/1.1" 200 10977
[2021-03-09 20:52:44,917] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2021-03-09 20:52:44,929] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2021-03-09 20:52:44,934] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2021-03-09 20:52:44,939] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2021-03-09 20:52:44,940] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2021-03-09 20:52:44,942] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2021-03-09 20:52:50,658] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/ HTTP/1.1" 201 9908
[2021-03-09 20:52:57,361] [log.py:224] [log:log_response] [WARNING]- Bad Request: /api/UserAnother/
[2021-03-09 20:52:57,361] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/UserAnother/ HTTP/1.1" 400 9858
[2021-03-09 20:53:01,524] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/ HTTP/1.1" 201 9908
[2021-03-09 20:53:06,667] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/UserAnother/1/
Traceback (most recent call last):
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 656, in get_context
    raw_data_put_form = self.get_raw_data_form(data, view, 'PUT', request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 567, in get_raw_data_form
    content = renderer.render(data, accepted, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UserModel is not JSON serializable
[2021-03-09 20:53:06,669] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /api/UserAnother/1/ HTTP/1.1" 500 145484
[2021-03-09 20:53:09,264] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/UserAnother/1/
Traceback (most recent call last):
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 656, in get_context
    raw_data_put_form = self.get_raw_data_form(data, view, 'PUT', request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 567, in get_raw_data_form
    content = renderer.render(data, accepted, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UserModel is not JSON serializable
[2021-03-09 20:53:09,265] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /api/UserAnother/1/ HTTP/1.1" 500 145621
[2021-03-09 20:53:09,878] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/UserAnother/1/
Traceback (most recent call last):
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 656, in get_context
    raw_data_put_form = self.get_raw_data_form(data, view, 'PUT', request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 567, in get_raw_data_form
    content = renderer.render(data, accepted, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UserModel is not JSON serializable
[2021-03-09 20:53:09,879] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /api/UserAnother/1/ HTTP/1.1" 500 145621
[2021-03-09 20:53:11,117] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/UserAnother/1/
Traceback (most recent call last):
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 656, in get_context
    raw_data_put_form = self.get_raw_data_form(data, view, 'PUT', request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 567, in get_raw_data_form
    content = renderer.render(data, accepted, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UserModel is not JSON serializable
[2021-03-09 20:53:11,118] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /api/UserAnother/1/ HTTP/1.1" 500 145621
[2021-03-09 20:53:11,821] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/UserAnother/1/
Traceback (most recent call last):
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 656, in get_context
    raw_data_put_form = self.get_raw_data_form(data, view, 'PUT', request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 567, in get_raw_data_form
    content = renderer.render(data, accepted, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UserModel is not JSON serializable
[2021-03-09 20:53:11,824] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /api/UserAnother/1/ HTTP/1.1" 500 145621
[2021-03-09 20:53:23,043] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/Serializers.py changed, reloading.
[2021-03-09 20:53:23,665] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:53:24,401] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/ HTTP/1.1" 200 11327
[2021-03-09 20:53:24,421] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2021-03-09 20:53:24,442] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2021-03-09 20:53:24,443] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2021-03-09 20:53:24,445] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2021-03-09 20:53:24,446] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2021-03-09 20:53:24,446] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2021-03-09 20:53:35,051] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/Serializers.py changed, reloading.
[2021-03-09 20:53:35,688] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:53:36,466] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/UserAnother/1/
Traceback (most recent call last):
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 656, in get_context
    raw_data_put_form = self.get_raw_data_form(data, view, 'PUT', request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 567, in get_raw_data_form
    content = renderer.render(data, accepted, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UserModel is not JSON serializable
[2021-03-09 20:53:36,467] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /api/UserAnother/1/ HTTP/1.1" 500 145607
[2021-03-09 20:53:37,203] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/UserAnother/1/
Traceback (most recent call last):
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 656, in get_context
    raw_data_put_form = self.get_raw_data_form(data, view, 'PUT', request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 567, in get_raw_data_form
    content = renderer.render(data, accepted, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UserModel is not JSON serializable
[2021-03-09 20:53:37,205] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /api/UserAnother/1/ HTTP/1.1" 500 145607
[2021-03-09 20:54:01,307] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/Serializers.py changed, reloading.
[2021-03-09 20:54:01,757] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:54:02,053] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/ HTTP/1.1" 200 11685
[2021-03-09 20:54:02,072] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2021-03-09 20:54:02,078] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2021-03-09 20:54:02,081] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2021-03-09 20:54:02,085] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2021-03-09 20:54:02,090] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2021-03-09 20:54:02,090] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2021-03-09 20:55:04,115] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/Serializers.py changed, reloading.
[2021-03-09 20:55:04,780] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:55:05,218] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/UserAnother/1/
Traceback (most recent call last):
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 656, in get_context
    raw_data_put_form = self.get_raw_data_form(data, view, 'PUT', request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 567, in get_raw_data_form
    content = renderer.render(data, accepted, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UserModel is not JSON serializable
[2021-03-09 20:55:05,219] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /api/UserAnother/1/ HTTP/1.1" 500 145597
[2021-03-09 20:55:05,967] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/UserAnother/1/
Traceback (most recent call last):
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 656, in get_context
    raw_data_put_form = self.get_raw_data_form(data, view, 'PUT', request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 567, in get_raw_data_form
    content = renderer.render(data, accepted, context)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UserModel is not JSON serializable
[2021-03-09 20:55:05,968] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /api/UserAnother/1/ HTTP/1.1" 500 145597
[2021-03-09 20:55:29,540] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/Serializers.py changed, reloading.
[2021-03-09 20:55:29,965] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:55:31,500] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/ HTTP/1.1" 200 11685
[2021-03-09 20:55:31,518] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2021-03-09 20:55:31,530] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2021-03-09 20:55:31,536] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2021-03-09 20:55:31,537] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2021-03-09 20:55:31,537] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2021-03-09 20:55:31,538] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2021-03-09 20:56:12,844] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/ HTTP/1.1" 200 12355
[2021-03-09 20:56:17,342] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/?user=1 HTTP/1.1" 200 11680
[2021-03-09 20:56:42,503] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/models.py changed, reloading.
[2021-03-09 20:56:43,040] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:57:44,830] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/models.py changed, reloading.
[2021-03-09 20:57:45,251] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:57:51,559] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/models.py changed, reloading.
[2021-03-09 20:57:51,935] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:58:10,465] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/models.py changed, reloading.
[2021-03-09 20:58:10,853] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:58:35,459] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/models.py changed, reloading.
[2021-03-09 20:58:35,870] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:58:43,489] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/?user=1 HTTP/1.1" 200 12020
[2021-03-09 20:58:43,507] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2021-03-09 20:58:43,520] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2021-03-09 20:58:43,521] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2021-03-09 20:58:43,523] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2021-03-09 20:58:43,526] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2021-03-09 20:58:43,527] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2021-03-09 20:59:56,846] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/Serializers.py changed, reloading.
[2021-03-09 20:59:57,291] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 20:59:59,870] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/?user=1 HTTP/1.1" 200 11739
[2021-03-09 20:59:59,899] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2021-03-09 20:59:59,915] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2021-03-09 20:59:59,916] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2021-03-09 20:59:59,917] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2021-03-09 20:59:59,918] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2021-03-09 20:59:59,918] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2021-03-09 21:00:08,848] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/Serializers.py changed, reloading.
[2021-03-09 21:00:09,489] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:00:10,127] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/?user=1 HTTP/1.1" 200 11726
[2021-03-09 21:00:10,144] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2021-03-09 21:00:10,154] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2021-03-09 21:00:10,155] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2021-03-09 21:00:10,157] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2021-03-09 21:00:10,160] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2021-03-09 21:00:10,165] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2021-03-09 21:00:18,521] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1 HTTP/1.1" 301 0
[2021-03-09 21:00:18,547] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/ HTTP/1.1" 200 11757
[2021-03-09 21:01:53,859] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/views.py changed, reloading.
[2021-03-09 21:01:54,236] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:05:36,043] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/views.py changed, reloading.
[2021-03-09 21:05:36,684] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:05:37,770] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/ HTTP/1.1" 200 12339
[2021-03-09 21:05:37,800] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2021-03-09 21:05:37,809] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2021-03-09 21:05:37,814] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2021-03-09 21:05:37,816] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2021-03-09 21:05:37,821] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2021-03-09 21:05:37,822] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2021-03-09 21:05:39,926] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 10177
[2021-03-09 21:07:20,188] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/views.py changed, reloading.
[2021-03-09 21:07:20,609] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:07:20,918] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 10177
[2021-03-09 21:07:20,934] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2021-03-09 21:07:20,943] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2021-03-09 21:07:20,944] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2021-03-09 21:07:20,949] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2021-03-09 21:07:20,952] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2021-03-09 21:07:20,955] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2021-03-09 21:07:31,206] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 2
[2021-03-09 21:07:39,704] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 2
[2021-03-09 21:07:52,569] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 2
[2021-03-09 21:07:57,186] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 2
[2021-03-09 21:08:19,874] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/views.py changed, reloading.
[2021-03-09 21:08:20,418] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:08:21,145] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 2
[2021-03-09 21:08:25,980] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 2
[2021-03-09 21:08:30,021] [log.py:224] [log:log_response] [WARNING]- Method Not Allowed: /api/UserAnother/1/UerBlankChange/
[2021-03-09 21:08:30,022] [basehttp.py:157] [basehttp:log_message] [WARNING]- "PUT /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 405 45
[2021-03-09 21:10:27,143] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/Serializers.py changed, reloading.
[2021-03-09 21:10:27,564] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:10:29,723] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/UserAnother/1/UerBlankChange/
Traceback (most recent call last):
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'rest_framework.utils.serializer_helpers.ReturnDict'>`
[2021-03-09 21:10:29,724] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 500 84488
[2021-03-09 21:10:50,339] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/views.py changed, reloading.
[2021-03-09 21:10:50,881] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:10:51,949] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 346
[2021-03-09 21:15:48,370] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/views.py changed, reloading.
[2021-03-09 21:15:48,777] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:18:04,337] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/views.py changed, reloading.
[2021-03-09 21:18:05,285] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:18:05,801] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 346
[2021-03-09 21:18:08,709] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 2
[2021-03-09 21:18:23,549] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 346
[2021-03-09 21:18:46,398] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/views.py changed, reloading.
[2021-03-09 21:18:46,902] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:18:48,462] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 346
[2021-03-09 21:18:51,325] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 2
[2021-03-09 21:18:56,706] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 347
[2021-03-09 21:20:18,947] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/Serializers.py changed, reloading.
[2021-03-09 21:20:19,511] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:20:31,484] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 128
[2021-03-09 21:20:40,044] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 128
[2021-03-09 21:20:43,032] [log.py:224] [log:log_response] [WARNING]- Bad Request: /api/UserAnother/1/UerBlankChange/
[2021-03-09 21:20:43,033] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 400 108
[2021-03-09 21:21:57,760] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/views.py changed, reloading.
[2021-03-09 21:21:58,508] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:21:59,967] [log.py:224] [log:log_response] [WARNING]- Bad Request: /api/UserAnother/1/UerBlankChange/
[2021-03-09 21:21:59,968] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 400 108
[2021-03-09 21:22:13,313] [log.py:224] [log:log_response] [WARNING]- Bad Request: /api/UserAnother/1/UerBlankChange/
[2021-03-09 21:22:13,313] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 400 108
[2021-03-09 21:22:14,425] [log.py:224] [log:log_response] [WARNING]- Bad Request: /api/UserAnother/1/UerBlankChange/
[2021-03-09 21:22:14,426] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 400 108
[2021-03-09 21:22:15,554] [log.py:224] [log:log_response] [WARNING]- Bad Request: /api/UserAnother/1/UerBlankChange/
[2021-03-09 21:22:15,554] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 400 108
[2021-03-09 21:22:24,311] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 201 128
[2021-03-09 21:22:52,420] [log.py:224] [log:log_response] [WARNING]- Unauthorized: /api/UserAnother/1/UerBlankChange/
[2021-03-09 21:22:52,421] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 401 44
[2021-03-09 21:23:23,097] [log.py:224] [log:log_response] [WARNING]- Unauthorized: /api/UserAnother/1/UerBlankChange/
[2021-03-09 21:23:23,098] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 401 44
[2021-03-09 21:23:39,551] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/BaseConfig/Response.py changed, reloading.
[2021-03-09 21:23:40,221] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:23:40,917] [log.py:224] [log:log_response] [WARNING]- Unauthorized: /api/UserAnother/1/UerBlankChange/
[2021-03-09 21:23:40,917] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 401 44
[2021-03-09 21:24:05,802] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/BaseConfig/Response.py changed, reloading.
[2021-03-09 21:24:06,339] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:24:06,955] [log.py:224] [log:log_response] [WARNING]- Unauthorized: /api/UserAnother/1/UerBlankChange/
[2021-03-09 21:24:06,956] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 401 44
[2021-03-09 21:24:17,717] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/BaseConfig/Response.py changed, reloading.
[2021-03-09 21:24:18,165] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:24:18,930] [log.py:224] [log:log_response] [WARNING]- Unauthorized: /api/UserAnother/1/UerBlankChange/
[2021-03-09 21:24:18,930] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 401 29
[2021-03-09 21:24:21,391] [log.py:224] [log:log_response] [WARNING]- Unauthorized: /api/UserAnother/1/UerBlankChange/
[2021-03-09 21:24:21,392] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 401 29
[2021-03-09 21:24:36,543] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:24:39,082] [log.py:224] [log:log_response] [WARNING]- Unauthorized: /api/UserAnother/1/UerBlankChange/
[2021-03-09 21:24:39,083] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 401 29
[2021-03-09 21:24:46,385] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 201 128
[2021-03-09 21:25:19,643] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/views.py changed, reloading.
[2021-03-09 21:25:20,060] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:25:22,662] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/UserAnother/1/UerBlankChange/
Traceback (most recent call last):
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/adminuser/PycharmProjects/NovelProject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/adminuser/PycharmProjects/NovelProject/apps/user/views.py", line 146, in UerBlankChange
    _object.UserBalance = _object.UserBalance + float(blank_change)
TypeError: unsupported operand type(s) for +: 'decimal.Decimal' and 'float'
[2021-03-09 21:25:22,662] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 500 96233
[2021-03-09 21:25:37,584] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/views.py changed, reloading.
[2021-03-09 21:25:38,041] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:25:40,071] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 201 128
[2021-03-09 21:25:42,929] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:25:46,977] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 201 128
[2021-03-09 21:25:49,425] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 201 128
[2021-03-09 21:25:58,853] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:26:02,813] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 128
[2021-03-09 21:26:08,895] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 201 128
[2021-03-09 21:26:17,029] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 128
[2021-03-09 21:27:03,331] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/views.py changed, reloading.
[2021-03-09 21:27:03,778] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:27:04,340] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 128
[2021-03-09 21:27:09,704] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 201 128
[2021-03-09 21:27:14,192] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 128
[2021-03-09 21:27:17,366] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 201 128
[2021-03-09 21:27:18,207] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 201 128
[2021-03-09 21:27:18,684] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 201 128
[2021-03-09 21:27:19,079] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 201 128
[2021-03-09 21:28:44,707] [autoreload.py:240] [autoreload:trigger_reload] [INFO]- /home/adminuser/PycharmProjects/NovelProject/apps/user/views.py changed, reloading.
[2021-03-09 21:28:45,648] [autoreload.py:617] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-03-09 21:28:48,159] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 200 128
[2021-03-09 21:28:51,852] [log.py:224] [log:log_response] [WARNING]- Method Not Allowed: /api/UserAnother/1/UerBlankChange/
[2021-03-09 21:28:51,852] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 405 46
[2021-03-09 21:28:56,382] [basehttp.py:157] [basehttp:log_message] [INFO]- "PUT /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 201 128
[2021-03-09 21:28:58,118] [basehttp.py:157] [basehttp:log_message] [INFO]- "PUT /api/UserAnother/1/UerBlankChange/ HTTP/1.1" 201 128
